# Für Syntax-Higlighting und Autocomplete dieses Plugin installieren
# und bei schema die URL des GraphQL-Endpunktes eintragen:
# https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql
schema: 'https://git.sanberlin.com/graphql'
documents: 'app/**/*.{graphql,js,ts,jsx,tsx}'
