// Components
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import WpExternNavigation from '@/components/WpExternNavigation';
import WpMainNavigation from '@/components/WpMainNavigation';
import WpSubNavigation from '@/components/WpSubNavigation';

// SCSS
import '@/sass/style.scss';
import type { Metadata } from 'next';

// Fonts
import { Lato, Roboto } from 'next/font/google';

const robotoStyles = Roboto({
	subsets: ['latin'],
	weight: ['300', '400', '700'],
	style: 'normal',
	display: 'swap',
	variable: '--font-roboto',
});

const latoStyles = Lato({
	subsets: ['latin'],
	weight: ['700'],
	style: 'normal',
	display: 'swap',
	variable: '--font-lato',
});

// Metadata
export const metadata: Metadata = {
	title: 'Wordpress React Next App',
	description: 'Generated by create next app',
	icons: [{ url: '/favicon.svg', type: 'image/svg+xml' }],
};

// EXPORT
export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="de">
			<body className={`${robotoStyles.variable} ${latoStyles.variable}`}>
				{/* Header */}
				<div className="info">Header</div>
				<Header />

				{/* WpMainNavigation */}
				<div className="info">Main Navigation</div>
				<WpMainNavigation />

				{/* WpSubNavigation */}
				<div className="info">Sub Navigation</div>
				<WpSubNavigation />

				{/* Content */}
				<div className="info">Content</div>
				<main className="wp-content">{children}</main>

				{/* WpExternNavigation */}
				<div className="info">Extern Navigation</div>
				<WpExternNavigation />

				{/* Footer */}
				<div className="info">Footer with Legal Navigation</div>
				<Footer />
			</body>
		</html>
	);
}
