// Components
import Footer from '@/components/Footer';
import Header from '@/components/Header';

// SCSS
import '@/sass/style.scss';
import type { Metadata } from 'next';

// Fonts
import { Karla, Merriweather } from 'next/font/google';

const karlaStyles = Karla({
	subsets: ['latin'],
	weight: ['500', '800'],
	style: 'normal',
	display: 'swap',
	variable: '--font-karla',
});

const merriweatherStyles = Merriweather({
	subsets: ['latin'],
	weight: ['300', '400', '700', '900'],
	style: ['italic', 'normal'],
	display: 'swap',
	variable: '--font-merriweather',
});

// Metadata
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	icons: [{ url: '/favicon.svg', type: 'image/svg+xml' }],
};

// EXPORT
export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="de">
			<body
				className={`${karlaStyles.variable} ${merriweatherStyles.variable}`}
			>
				<Header />
				<div className="site-content">{children}</div>
				<Footer />
			</body>
		</html>
	);
}
